//! The compiler side of the bytecode boundary: everything that produces a
//! runnable [`Program`] from Scarlet source. The ISA, [`Program`], the NaN-boxed
//! `value` and the heap live in `scarlet_vm` and are re-exported here, so
//! `scarlet_core::bytecode::*` is the one import for both halves of the contract.

mod analysis;
pub mod compiler;
mod prelude;
pub mod prelude_bindings;
mod session;

pub(crate) use binop::{BinopKind, ShortCircuitOp, ValueBinop, specialize_binop};
pub use compiler::*;
pub use prelude_bindings::{CtorRef, PreludeBindings, TypeRef};
pub use scarlet_vm::bytecode::*;
pub use session::{HoverFact, IncrementalSession, Watermark};

/// Resolve an `@vm(name)` intrinsic key to its VM opcode. The only
/// string→Op mapping; analysis calls it while registering the stdlib so an
/// unknown key errors at the annotation, not during codegen.
fn builtin_op(name: &str) -> Option<Op> {
    Some(match name {
        "println" => Op::Print,
        "string__inspect" => Op::ToString,
        "internal__stack_depth" => Op::StackDepth,
        "internal__live_subjects" => Op::LiveSubjects,
        "internal__blocking_threads" => Op::BlockingThreads,
        "io__read_file" => Op::FileRead,
        "io__write_file" => Op::FileWrite,
        "net__listen" => Op::TcpListen,
        "net__accept" => Op::TcpAccept,
        "net__connect" => Op::TcpConnect,
        "net__connect_until" => Op::TcpConnectUntil,
        "net__close" => Op::TcpCloseServer,
        "net__give" => Op::TcpGive,
        "net__local_addr" => Op::TcpLocalAddr,
        "net__resolve" => Op::DnsResolve,
        "net__resolve_until" => Op::DnsResolveUntil,
        "address__parse" => Op::IpParse,
        "socket__read" => Op::TcpRead,
        "socket__read_until" => Op::TcpReadUntil,
        "socket__write" => Op::TcpWrite,
        "socket__write_parts" => Op::TcpWriteParts,
        "socket__close" => Op::TcpClose,
        "tls__handshake" => Op::TlsHandshake,
        "tls__handshake_until" => Op::TlsHandshakeUntil,
        "tls__read" => Op::TlsRead,
        "tls__read_until" => Op::TlsReadUntil,
        "tls__write" => Op::TlsWrite,
        "tls__close" => Op::TlsClose,
        "port__spawn" => Op::PortSpawn,
        "port__read" => Op::TcpRead,
        "port__read_until" => Op::TcpReadUntil,
        "port__write" => Op::TcpWrite,
        "port__write_parts" => Op::TcpWriteParts,
        "port__close" => Op::PortClose,
        "string__split" => Op::StrSplit,
        "string__length" => Op::StrLen,
        "string__contains" => Op::StrContains,
        "string__trim" => Op::StrTrim,
        "string__to_graphemes" => Op::StrToGraphemes,
        "int__to_string" => Op::IntToString,
        "int__from_string" => Op::IntFromString,
        "int__bitwise_and" => Op::BitAnd,
        "int__bitwise_or" => Op::BitOr,
        "int__bitwise_xor" => Op::BitXor,
        "int__bitwise_not" => Op::BitNot,
        "int__bitwise_shift_left" => Op::BitShl,
        "int__bitwise_shift_right" => Op::BitShr,
        "array__length" => Op::ArrayLen,
        "binary__from_string" => Op::BinFromString,
        "binary__to_string" => Op::BinToString,
        "binary__bit_size" => Op::BinBitSize,
        "binary__byte_size" => Op::BinByteSize,
        "binary__slice_bits" => Op::BinSlice,
        "binary__append" => Op::BinAppend,
        "binary__index_of" => Op::BinIndexOf,
        "binary__byte_at" => Op::BinByteAt,
        "binary__parse_int" => Op::BinParseInt,
        "binary__eq_ignore_ascii_case" => Op::BinEqIgnoreAsciiCase,
        "binary__to_ascii_lower" => Op::BinToAsciiLower,
        "binary__from_int_ascii" => Op::BinFromIntAscii,
        "http__parse_head" => Op::HttpParseHead,
        "http__parse_response_head" => Op::HttpParseResponseHead,
        "http__framing" => Op::HttpFraming,
        "http__chunk_decode" => Op::HttpChunkDecode,
        "http__header_get" => Op::HttpHeaderGet,
        "http__header_has" => Op::HttpHeaderHas,
        "http__headers_valid" => Op::HttpHeadersValid,
        "http__serialize_head" => Op::HttpSerializeHead,
        "float__floor" => Op::FloatFloor,
        "float__ceil" => Op::FloatCeil,
        "float__round" => Op::FloatRound,
        "float__truncate" => Op::FloatTruncate,
        "float__from_int" => Op::FloatFromInt,
        "float__to_string" => Op::FloatToString,
        "process__spawn" => Op::ProcessSpawn,
        "process__spawn_unlinked" => Op::ProcessSpawnUnlinked,
        "process__kill" => Op::ProcessKill,
        "process__self" => Op::ProcessSelf,
        "process__monitor" => Op::ProcessMonitor,
        "process__demonitor" => Op::ProcessDemonitor,
        "process__supervisor" => Op::SupervisorNew,
        "process__worker" => Op::SupervisorWorker,
        "process__factory" => Op::FactoryNew,
        "process__lookup_or_start" => Op::FactoryLookupOrStart,
        "process__lookup" => Op::FactoryLookup,
        "process__supervised" => Op::SupervisedOf,
        "process__parent" => Op::SupervisedParent,
        "process__children" => Op::SupervisedChildren,
        "process__count" => Op::SupervisedCount,
        "process__info" => Op::SupervisedInfo,
        "process__watch" => Op::WatchNew,
        "process__unwatch" => Op::WatchCancel,
        "process__worker_on_each" => Op::SupervisorWorkerOnEach,
        "process__start_in" => Op::FactorySpawn,
        "process__sleep" => Op::Sleep,
        "process__subject" => Op::SubjectNew,
        "process__send" => Op::SubjectSend,
        "process__send_urgent" => Op::SubjectSendUrgent,
        "process__receive" => Op::SubjectReceive,
        "process__receive_until" => Op::SubjectReceiveUntil,
        "time__monotonic" => Op::Monotonic,
        "time__epoch_ms" => Op::WallClock,
        "crypto__random_bytes" => Op::RandomBytes,
        "crypto__sha256" => Op::Sha256,
        "crypto__sha512" => Op::Sha512,
        "crypto__hmac_sha256" => Op::HmacSha256,
        "crypto__const_eq" => Op::ConstEq,
        "crypto__p256_verify" => Op::P256Verify,
        "crypto__ed25519_verify" => Op::Ed25519Verify,
        "os__argv" => Op::Argv,
        "os__env" => Op::EnvMap,
        "map__get" => Op::MapGet,
        "map__has" => Op::MapHas,
        "map__keys" => Op::MapKeys,
        "map__values" => Op::MapValues,
        "map__size" => Op::MapSize,
        "map__new" => Op::MapNew,
        "map__set" => Op::MapSet,
        "map__delete" => Op::MapDelete,
        "map__to_list" => Op::MapToList,
        "json__parse_binary" => Op::JsonParse,
        "json__kind" => Op::JsonKind,
        "json__len" => Op::JsonLen,
        "json__field" => Op::JsonField,
        "json__index" => Op::JsonIndex,
        "json__entries" => Op::JsonEntries,
        "json__elements" => Op::JsonElements,
        "json__string" => Op::JsonString,
        "json__int" => Op::JsonInt,
        "json__int_text" => Op::JsonIntText,
        "json__float" => Op::JsonFloat,
        "json__bool" => Op::JsonBool,
        "json__encode" => Op::JsonEncode,
        "wire__encode" => Op::WireEncode,
        "wire__decode" => Op::WireDecode,
        _ => return None,
    })
}
