[workspace]
members = [
    "crates/scarlet_vm",
    "crates/scarlet_syntax",
    "crates/scarlet_types",
    "crates/scarlet_core",
    "crates/scarlet",
    "crates/xtask",
]
resolver = "2"

[workspace.dependencies]
indexmap = "2"
cranelift-codegen = "0.133.1"
cranelift-frontend = "0.133.1"
cranelift-module = "0.133.1"
cranelift-jit = "0.133.1"
cranelift-native = "0.133.1"

[profile.release]
strip = true
lto = "thin"
codegen-units = 1

[profile.profiling]
inherits = "release"
strip = false
debug = true
